name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and Push Docker image
        run: |
          REPOSITORY_NAME=${{ github.repository }}
          IMAGE_NAME=ghcr.io/${REPOSITORY_NAME,,}:latest
          docker buildx build --platform linux/amd64,linux/arm64,linux/s390x -t $IMAGE_NAME --push .
